### ISSUE TITLE
Support for WordPress 5.0 and beyond?

### ISSUE THREAD

**Issue by nyckelplaya** [dashkevych/goedemorgen#4]
Hello! This isn't an issue per se. Just wondering if you are following the changes coming with Gutenberg and WordPress 5.0. Everything will continue working with the Classic Editor installed, but was wondering if you will continue providing support for the theme past 5.0? I hope so - it's a great theme. I personally will not be switching to Gutenberg anytime soon, but was just curious what your plans are with the theme. Thanks!

**Comment by dashkevych** [comment]
Hello,

The theme is built on WordPress standards and it does not have any custom functionalities for the editor, so it should work fine with Gutenberg and WordPress 5.0.

Currently, the theme does not have any specially designed styles for Gutenberg blocks (for example, quotes) but it should not break the site. It will just use default Gutenberg styles.

We will definitely continue providing support for the theme past 5.0.

Thanks!

**Comment by nyckelplaya** [comment]
Perfect, thanks so much!
